services:
  web:
    build: .
    container_name: ticky_app
    ports:
      - 8913:8000
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    networks:
      - app-network
  
  db:
    image: postgres:16
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - 5432:5432

volumes:
  postgres_db:
    driver: local
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge