# Generated by Django 5.2.1 on 2025-06-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('progress', 'progress'), ('completed', 'completed')], default='progress')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payement_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('organizer', 'organisateur'), ('user', 'Utilisateur')], default='user', max_length=32)),
            ],
        ),
    ]
