# Generated by Django 5.2.1 on 2025-06-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('organizer', 'organizer'), ('user', 'user')], default='user', max_length=32),
        ),
    ]
