# Generated by Django 5.2.1 on 2025-06-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payement',
            name='order',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='user.order'),
            preserve_default=False,
        ),
    ]
