name: Ticky deploy on VPS
on:
  push:
    branches: ["dilane"]
  pull_request: 
    branches: ["dilane"]
jobs:
  ticky:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: set up SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: whoami
      
      - name: Message
        run: echo 'All Done'
